language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn test:unit --coverage
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
  - rm -rf ./coverage
